<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAhQXZ6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAhQXZ6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMAhQXZ6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMAhQXZ6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMAhQXZ6\App_KernelDevDebugContainer([
    'container.build_hash' => 'MAhQXZ6',
    'container.build_id' => '664bab75',
    'container.build_time' => 1661875310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAhQXZ6');
