<?php

namespace ContainerLZWHrMn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6pysiGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B6pysiG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B6pysiG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jwt_auth' => ['privates', 'App\\Services\\JwtAuth', 'getJwtAuthService', true],
        ], [
            'jwt_auth' => 'App\\Services\\JwtAuth',
        ]);
    }
}
